# Generated by Django 5.2.9 on 2025-12-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_adresse_customuser_telephone_auditlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="produits/images/",
                verbose_name="Image du produit",
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="thumbnail",
            field=models.ImageField(
                blank=True, editable=False, null=True, upload_to="produits/thumbnails/"
            ),
        ),
    ]
