# Generated by Django 5.2.9 on 2025-12-26 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_produit_image_produit_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="image",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="thumbnail",
        ),
    ]
